/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.Mrbn;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int b1=0x7f040002;
        public static final int b2=0x7f040003;
        public static final int b3=0x7f040004;
        public static final int btnClose=0x7f04000b;
        public static final int btnNextScreen=0x7f040008;
        public static final int button=0x7f040005;
        public static final int email=0x7f040007;
        public static final int l1=0x7f040000;
        public static final int l2=0x7f040001;
        public static final int name=0x7f040006;
        public static final int txtEmail=0x7f04000a;
        public static final int txtName=0x7f040009;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
        public static final int screen1=0x7f020001;
        public static final int screen2=0x7f020002;
    }
    public static final class string {
        public static final int Mrbn_msg=0x7f030001;
        public static final int app_name=0x7f030000;
        public static final int email=0x7f030006;
        public static final int menu_settings=0x7f030002;
        public static final int my_button_text=0x7f030004;
        public static final int name=0x7f030005;
        public static final int title_activity_main=0x7f030003;
    }
}
